Repository boostcampaitech4lv23nlp2/final-project-level3-nlp-10, pull requests merged in 2023-02, with the labels that each got.

#5 Feature/DPR
  ml/config/dpr_config.yaml
  ml/data/__init__.py
  ml/data/make_dataset.py
  ml/model/dataloader.py
  ml/model/evaluate.py
  ml/model/models.py
  ml/model/retrieval.py
  ml/model/train.py
  ml/utils/__init__.py
  ml/utils/logger.py
Labels: enhancement

#23 Feature/app_STT
  app/backend/api.py
  app/backend/app_utils/__init__.py
  app/backend/app_utils/cache_load.py
  app/backend/app_utils/stt.py
  app/backend/model/__init__.py
  app/backend/server.py
  app/fronted/Boost2Note.py
Labels: enhancement

#27 Feature/app sentence seperation
  app/backend/app_utils/__init__.py
  app/backend/app_utils/cache_load.py
  app/backend/app_utils/data_process.py
  app/backend/server.py
  app/fronted/Boost2Note.py
Labels: enhancement

#18 Query Keyword 추출 및 생성
  app/backend/app_utils/cache_load.py
  app/backend/app_utils/extract_keyword.py
  app/backend/app_utils/key_bert.py
  app/backend/server.py
Labels: enhancement

#11 Feature/notebooks
  notebooks/EDA.ipynb
  notebooks/data_combine.ipynb
  notebooks/keybert.ipynb
  notebooks/preprocess.ipynb
Labels: documentation

#49 fix: server port 연결
  app/backend/server.py
  app/frontend/Boost2Note.py
Labels: bug

#43 STT post-processing
  app/backend/app_utils/__init__.py
  app/backend/app_utils/cache_load.py
  app/backend/app_utils/data_process.py
  app/backend/app_utils/stt.py
  app/backend/server.py
Labels: enhancement

#46 요약 모델 정량 평가를 위한 Evaluation Metrics
  notebooks/summarization_metrics.ipynb
Labels: enhancement

#15 Feature/fid
  DPR/dpr_train.py
  ml/config.yaml
  ml/data/make_dataset.py
  ml/main.py
  ml/model/dpr_train.py
  ml/model/fid_train.py
  ml/model/models.py
  ml/utils/dpr.py
  ml/utils/mrc/arguments.py
  ml/utils/mrc/retrieval.py
  ml/utils/mrc/trainer_qa.py
  ml/utils/mrc/utils_qa.py
Labels: enhancement

#53 TF-IDF를 이용한 키워드 추출 정리
  app/backend/app_utils/extract_keyword.py
  notebooks/extract_keyword_KR-WordRank.ipynb
  notebooks/extract_keyword_TF-IDF.ipynb
Labels: enhancement

#54 Feature/app
  app/backend/app_utils/extract_keyword.py
  app/backend/server.py
  app/frontend/Boost2Note.py
  app/frontend/pages/Total_Note.py
  notebooks/extract_keyword_KR-WordRank.ipynb
  notebooks/extract_keyword_TF-IDF.ipynb
Labels: bug

#52 Boost2Note v1.1.0
  DPR/dpr_train.py
  app/backend/app_utils/__init__.py
  app/backend/app_utils/cache_load.py
  app/backend/app_utils/data_process.py
  app/backend/app_utils/extract_keyword.py
  app/backend/app_utils/inference.py
  app/backend/app_utils/key_bert.py
  app/backend/app_utils/stt.py
  app/backend/model/retriever.py
  app/backend/server.py
  app/frontend/Boost2Note.py
  app/frontend/pages/Total_Note.py
  ml/config.yaml
  ml/data/make_dataset.py
  ml/main.py
  ml/model/dpr_train.py
  ml/model/fid_train.py
  ml/model/models.py
  ml/utils/dpr.py
  ml/utils/mrc/arguments.py
  ml/utils/mrc/retrieval.py
  ml/utils/mrc/trainer_qa.py
  ml/utils/mrc/utils_qa.py
  notebooks/extract_keyword_KR-WordRank.ipynb
  notebooks/extract_keyword_TF-IDF.ipynb
  notebooks/summarization_metrics.ipynb
Labels: enhancement
